[package]
name = "ferris-says"
version = "0.1.0"
authors = ["sukhvirdi7 <sukh.virdi2@mhra.gov.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"